# Generated by Django 4.2.19 on 2025-03-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French')], default='english', max_length=50, verbose_name='Язык курса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Материал урока')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Примеры')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Длительность урока (в минутах)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Позиция в курсе')),
                ('language_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50, verbose_name='Уровень языка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('option1', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Вариант ответа 1')),
                ('option2', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Вариант ответа 2')),
                ('option3', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Вариант ответа 3')),
                ('option4', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Вариант ответа 4')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='Проходной балл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French')], default='english', max_length=50, verbose_name='Изучаемый язык')),
                ('language_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50, verbose_name='Уровень языка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Количество набранных очков')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Текущий урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'прогресс',
                'verbose_name_plural': 'Прогрессы',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
